# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entry.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 137)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_for_description = QtWidgets.QLabel(self.centralwidget)
        self.label_for_description.setGeometry(QtCore.QRect(10, 10, 331, 20))
        self.label_for_description.setObjectName("label_for_description")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 50, 171, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_for_when = QtWidgets.QLabel(self.centralwidget)
        self.label_for_when.setGeometry(QtCore.QRect(190, 40, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_for_when.setFont(font)
        self.label_for_when.setScaledContents(False)
        self.label_for_when.setObjectName("label_for_when")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_for_description.setText(_translate("MainWindow", "<Description>"))
        self.label_for_when.setText(_translate("MainWindow", "€  <when?>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
