# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_entry_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(282, 351)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_field = QtWidgets.QLineEdit(self.centralwidget)
        self.name_field.setGeometry(QtCore.QRect(30, 20, 221, 25))
        self.name_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name_field.setAutoFillBackground(False)
        self.name_field.setInputMask("")
        self.name_field.setAlignment(QtCore.Qt.AlignCenter)
        self.name_field.setObjectName("name_field")
        self.amount_field = QtWidgets.QLineEdit(self.centralwidget)
        self.amount_field.setGeometry(QtCore.QRect(30, 60, 221, 25))
        self.amount_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.amount_field.setAutoFillBackground(False)
        self.amount_field.setInputMask("")
        self.amount_field.setAlignment(QtCore.Qt.AlignCenter)
        self.amount_field.setObjectName("amount_field")
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(110, 100, 151, 41))
        self.date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date.setObjectName("date")
        self.last_date = QtWidgets.QDateEdit(self.centralwidget)
        self.last_date.setGeometry(QtCore.QRect(110, 150, 151, 41))
        self.last_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.last_date.setObjectName("last_date")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 110, 41, 17))
        self.label.setObjectName("label")
        self.choose_monthly = QtWidgets.QRadioButton(self.centralwidget)
        self.choose_monthly.setGeometry(QtCore.QRect(10, 230, 112, 23))
        self.choose_monthly.setObjectName("choose_monthly")
        self.choose_yearly = QtWidgets.QRadioButton(self.centralwidget)
        self.choose_yearly.setGeometry(QtCore.QRect(10, 250, 112, 23))
        self.choose_yearly.setObjectName("choose_yearly")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(90, 300, 111, 25))
        self.ok_button.setObjectName("ok_button")
        self.checkBox_last_date = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_last_date.setGeometry(QtCore.QRect(10, 160, 92, 23))
        self.checkBox_last_date.setObjectName("checkBox_last_date")
        self.choose_once = QtWidgets.QRadioButton(self.centralwidget)
        self.choose_once.setGeometry(QtCore.QRect(10, 210, 112, 23))
        self.choose_once.setObjectName("choose_once")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "New Entry"))
        self.name_field.setPlaceholderText(_translate("MainWindow", "Name"))
        self.amount_field.setPlaceholderText(_translate("MainWindow", "Amount"))
        self.label.setText(_translate("MainWindow", "Date"))
        self.choose_monthly.setText(_translate("MainWindow", "Monthly"))
        self.choose_yearly.setText(_translate("MainWindow", "Yearly"))
        self.ok_button.setText(_translate("MainWindow", "OK"))
        self.checkBox_last_date.setText(_translate("MainWindow", "Last Date"))
        self.choose_once.setText(_translate("MainWindow", "Once"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
