# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_entry_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(170, 338)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_field = QtWidgets.QLineEdit(self.centralwidget)
        self.name_field.setGeometry(QtCore.QRect(30, 20, 113, 25))
        self.name_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name_field.setAutoFillBackground(False)
        self.name_field.setInputMask("")
        self.name_field.setAlignment(QtCore.Qt.AlignCenter)
        self.name_field.setObjectName("name_field")
        self.amount_field = QtWidgets.QLineEdit(self.centralwidget)
        self.amount_field.setGeometry(QtCore.QRect(30, 60, 113, 25))
        self.amount_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.amount_field.setAutoFillBackground(False)
        self.amount_field.setInputMask("")
        self.amount_field.setAlignment(QtCore.Qt.AlignCenter)
        self.amount_field.setObjectName("amount_field")
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(30, 120, 110, 26))
        self.date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date.setObjectName("date")
        self.last_date = QtWidgets.QDateEdit(self.centralwidget)
        self.last_date.setGeometry(QtCore.QRect(30, 180, 110, 26))
        self.last_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.last_date.setObjectName("last_date")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 100, 41, 17))
        self.label.setObjectName("label")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 230, 112, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 250, 112, 23))
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 290, 71, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 290, 71, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 160, 92, 23))
        self.checkBox.setObjectName("checkBox")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(30, 210, 112, 23))
        self.radioButton.setObjectName("radioButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "New Entry"))
        self.name_field.setPlaceholderText(_translate("MainWindow", "Name"))
        self.amount_field.setPlaceholderText(_translate("MainWindow", "Amount"))
        self.label.setText(_translate("MainWindow", "Date"))
        self.radioButton_2.setText(_translate("MainWindow", "Monthly"))
        self.radioButton_3.setText(_translate("MainWindow", "Yearly"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.checkBox.setText(_translate("MainWindow", "Last Date"))
        self.radioButton.setText(_translate("MainWindow", "Once"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
